version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3"
  # jobs:
  #   pre_build:
  #     - python -m sphinx

python:
  # Install our python package before building the docs
  install:
    - requirements: requirements.txt
    - method: pip
      path: .

sphinx:
  configuration: docs/source/conf.py

# Optionally build your docs in additional formats such as PDF and ePub
formats:
  - pdf
  - epub