version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.11"
  jobs:
    pre_build:
      - python -m sphinx -b linkcheck docs/ _build/linkcheck

sphinx:
  configuration: docs/source/conf.py

python:
  # Install our python package before building the docs
  install:
    - requirements: requirements.txt
    - method: pip
      path: .